name: Deploy to Altervista
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Altervista
        uses: dreadnaut/deploy-to-altervista@v0.1
        with:
          ftp-username: udavenere
          ftp-password: ${{ secrets.ALTERVISTA_FTP_PASSWORD }}
          exclude-patterns: |
            README.md
